import { getRedisConnection } from "../queue/queue.js";
import { logger } from "./logger.js";

/**
 * A ceiling on how fast someone may guess a password.
 *
 * ============================================================
 * WHAT THIS IS FOR, AND WHAT IT IS NOT FOR
 * ============================================================
 *
 * Found by auditing the auth path on 2026-08-18: there was no limit of any kind
 * on `/auth/admin` or `/auth/employee`. Both are unauthenticated by definition
 * and reachable from the internet.
 *
 * The exposure is narrower than "no rate limiting" sounds, and worth stating
 * precisely rather than dramatically:
 *
 *   Employee access codes are 10 characters from a 31-letter alphabet — about
 *   49 bits, generated by the platform and never chosen by a caller. Guessing
 *   one online is not a realistic attack and this limiter is not what stops it.
 *
 *   ADMIN PASSWORDS ARE CHOSEN BY A PERSON. That is the real exposure. There are
 *   two admin accounts, both in use, and an admin session reads every business's
 *   customer conversations. scrypt makes each attempt expensive; nothing made
 *   the NUMBER of attempts expensive.
 *
 * The shared bootstrap password is already retired in production — verified via
 * /auth/admin/bootstrap — so that door is closed and this does not reopen it.
 *
 * ============================================================
 * TWO DESIGN DECISIONS THAT COULD EACH HAVE MADE THIS WORSE
 * ============================================================
 *
 * IT COUNTS PER SOURCE, NOT PER ACCOUNT. Locking an identifier after N failures
 * is the obvious design and it hands anybody a way to lock the owner out of
 * their own console by typing their email wrongly ten times. A limiter that
 * converts into a denial of service against the person it protects is not a
 * security control. The identifier is recorded in the log line and nowhere else.
 *
 * IT FAILS OPEN. If Redis is unreachable, sign-in proceeds unthrottled. That is
 * the opposite of `sharedPasswordRetired`, which fails closed, and the
 * difference is which thing is load-bearing: that check guards a KNOWN weak
 * credential, so denying is safe. This is defence in depth over a credential
 * that is still verified by scrypt either way — so a Redis blip must not lock
 * two admins out of the platform they run.
 */

/** Failures from one source before it is asked to wait. */
const MAX_FAILURES = 10;

/** How long the count is remembered, and how long the cooldown lasts. */
const WINDOW_SECONDS = 15 * 60;

/**
 * The caller's address, as seen through Caddy.
 *
 * `x-forwarded-for` is a list; the FIRST entry is the client and the rest are
 * proxies. Taking the last would count every attempt against Caddy's own
 * address and throttle the whole platform after ten failures by anybody.
 *
 * A missing header means the request did not come through the proxy, which in
 * this deployment means it came from inside the compose network. Those share one
 * bucket under a name that says so rather than being exempted.
 */
export function clientKey(headers: { get(name: string): string | null }): string {
  const forwarded = headers.get("x-forwarded-for");
  const first = forwarded?.split(",")[0]?.trim();
  return first && first.length > 0 ? first : "internal";
}

/** True when this source has run out of attempts and should be refused. */
export async function loginBlocked(source: string): Promise<boolean> {
  try {
    const value = await getRedisConnection().get(key(source));
    return Number(value ?? 0) >= MAX_FAILURES;
  } catch (err) {
    // See the header comment: open, deliberately.
    logger.warn({ err }, "Login throttle unavailable — allowing the attempt");
    return false;
  }
}

/**
 * Records a failure and returns how many remain.
 *
 * The window is refreshed on every failure rather than fixed from the first, so
 * a patient attacker cannot pace themselves at nine per window forever.
 */
export async function recordLoginFailure(source: string, identifier: string): Promise<void> {
  try {
    const redis = getRedisConnection();
    const count = await redis.incr(key(source));
    await redis.expire(key(source), WINDOW_SECONDS);
    if (count >= MAX_FAILURES) {
      // Logged once at the threshold rather than on every attempt after it: the
      // interesting event is the lockout, and repeating it turns a signal into
      // the noise it is competing with.
      logger.warn(
        { source, identifier, failures: count },
        "Sign-in attempts from this source are now being refused"
      );
    }
  } catch (err) {
    logger.warn({ err }, "Could not record a failed sign-in");
  }
}

/**
 * Clears the count after a successful sign-in.
 *
 * Without this, somebody who mistypes nine times and then gets it right is one
 * typo away from a lockout for the rest of the window — which is exactly the
 * person this is not aimed at.
 */
export async function clearLoginFailures(source: string): Promise<void> {
  try {
    await getRedisConnection().del(key(source));
  } catch {
    // Nothing to do: the count expires on its own.
  }
}

const key = (source: string) => `nexus:login-failures:${source}`;
