// Nothing limited how fast a password could be guessed.
//
// Found on 2026-08-18 auditing the API routes and the admin screen. `/auth/admin`
// and `/auth/employee` are unauthenticated by definition and reachable from the
// internet, and neither had a limit of any kind.
//
// THE EXPOSURE IS NARROWER THAN "NO RATE LIMITING" SOUNDS, and worth stating
// precisely rather than dramatically:
//
//   Employee access codes are 10 characters from a 31-letter alphabet — about
//   49 bits, generated by the platform and never chosen by a caller. Guessing
//   one online is not a realistic attack, and this is not what stops it.
//
//   ADMIN PASSWORDS ARE CHOSEN BY A PERSON. That is the real exposure. Two admin
//   accounts exist, both in use, and an admin session reads every business's
//   customer conversations. scrypt makes each attempt expensive; nothing made
//   the NUMBER of attempts expensive.
//
// The shared bootstrap password is already retired in production — checked
// against /auth/admin/bootstrap, which answered sharedPasswordRetired: true —
// so that door was already closed and this does not reopen it.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (...p) => readFileSync(join(here, "..", "..", "..", ...p), "utf8");

const THROTTLE = read("apps", "api", "src", "lib", "login-throttle.ts");
const ADMIN = read("apps", "api", "src", "routes", "admin-auth.ts");
const EMPLOYEE = read("apps", "api", "src", "routes", "employee-auth.ts");

test("both unauthenticated sign-in paths are throttled", () => {
  for (const [name, src] of [["admin", ADMIN], ["employee", EMPLOYEE]]) {
    assert.match(src, /const source = clientKey\(c\.req\.raw\.headers\);/, `${name} reads no source`);
    assert.match(src, /if \(await loginBlocked\(source\)\) \{/, `${name} does not check the throttle`);
    assert.match(src, /429/, `${name} does not refuse with 429`);
  }
});

test("it counts per SOURCE and never per account", () => {
  // Locking an identifier after N failures is the obvious design and it hands
  // anybody a way to lock the owner out of their own console by typing their
  // email wrongly ten times. A limiter that becomes a denial of service against
  // the person it protects is not a security control.
  assert.match(THROTTLE, /const key = \(source: string\) => `nexus:login-failures:\$\{source\}`;/);

  // The identifier is passed only so the log line can name it.
  assert.match(THROTTLE, /recordLoginFailure\(source: string, identifier: string\)/);
  assert.ok(
    !/`nexus:login-failures:\$\{identifier\}`/.test(THROTTLE),
    "the identifier must never be part of the key"
  );
});

test("it fails OPEN, unlike the bootstrap check which fails closed", () => {
  // Different things are load-bearing. sharedPasswordRetired guards a KNOWN weak
  // credential, so denying on error is safe. This is defence in depth over a
  // credential still verified by scrypt either way — so a Redis blip must not
  // lock two admins out of the platform they run.
  const blocked = THROTTLE.slice(THROTTLE.indexOf("export async function loginBlocked"));
  assert.match(blocked.slice(0, 500), /catch \(err\) \{[\s\S]*?return false;/);
});

test("the throttle is checked BEFORE the credential is verified", () => {
  // A refused source should cost one Redis read, not an scrypt verification —
  // otherwise the limiter hands an attacker a cheap way to burn CPU.
  for (const src of [ADMIN, EMPLOYEE]) {
    const checkAt = src.indexOf("loginBlocked(source)");
    const verifyAt = Math.max(src.indexOf("verifySecret("), src.indexOf("verifyAccessCode("));
    assert.ok(checkAt > 0 && checkAt < verifyAt, "the throttle must be checked first");
  }
});

test("a success clears the count", () => {
  // Without this, somebody who mistypes nine times and then gets it right is one
  // typo from a lockout for the rest of the window — exactly the person this is
  // not aimed at.
  for (const src of [ADMIN, EMPLOYEE]) {
    assert.match(src, /await clearLoginFailures\(source\);/);
  }
});

test("the client is the FIRST forwarded address, not the last", () => {
  // x-forwarded-for is a list: client first, proxies after. Taking the last
  // counts every attempt against Caddy's own address and throttles the entire
  // platform after ten failures by anybody.
  assert.match(THROTTLE, /forwarded\?\.split\(","\)\[0\]\?\.trim\(\)/);

  // A request with no header did not come through the proxy, which here means
  // it came from inside the compose network. Those share one bucket under a
  // name that says so rather than being exempted.
  assert.match(THROTTLE, /: "internal"/);
});
