// Nothing limited how fast a password could be guessed.
//
// Found on 2026-08-18 auditing the API routes and the admin screen. `/auth/admin`
// and `/auth/employee` are unauthenticated by definition and reachable from the
// internet, and neither had a limit of any kind.
//
// THE EXPOSURE IS NARROWER THAN "NO RATE LIMITING" SOUNDS, and worth stating
// precisely rather than dramatically:
//
//   Employee access codes are 10 characters from a 31-letter alphabet — about
//   49 bits, generated by the platform and never chosen by a caller. Guessing
//   one online is not a realistic attack, and this is not what stops it.
//
//   ADMIN PASSWORDS ARE CHOSEN BY A PERSON. That is the real exposure. Two admin
//   accounts exist, both in use, and an admin session reads every business's
//   customer conversations. scrypt makes each attempt expensive; nothing made
//   the NUMBER of attempts expensive.
//
// The shared bootstrap password is already retired in production — checked
// against /auth/admin/bootstrap, which answered sharedPasswordRetired: true —
// so that door was already closed and this does not reopen it.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { withoutComments } from "../../../scripts/recurrence/source.mjs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (...p) => readFileSync(join(here, "..", "..", "..", ...p), "utf8");

const THROTTLE = read("apps", "api", "src", "lib", "login-throttle.ts");
const ADMIN = read("apps", "api", "src", "routes", "admin-auth.ts");
const EMPLOYEE = read("apps", "api", "src", "routes", "employee-auth.ts");

/**
 * Every route that checks a secret, found rather than listed.
 *
 * This test named admin-auth.ts and employee-auth.ts until 2026-08-24, which
 * covered both sign-in paths that exist and NOTHING ELSE. A third one -- a
 * customer portal, an API key exchange, a password reset that confirms the old
 * password -- would have been added, been unthrottled, and left this test
 * green, because the test knew only the two routes somebody had already
 * thought about.
 *
 * The population is derived from the thing that actually matters: a handler
 * comparing a caller-supplied secret against a stored hash. Both verifiers here
 * are deliberate, named, single-purpose functions, so looking for the call is
 * looking for the property.
 */
const VERIFIERS = ["verifySecret(", "verifyAccessCode(", "timingSafeEqual("];

function credentialRoutes() {
  const dir = join(here, "..", "src", "routes");
  const found = [];
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".ts")) continue;
    const src = readFileSync(join(dir, file), "utf8");
    // withoutComments rather than an inline pair of regexes: a comment naming
    // a verifier must not make a route look like it checks one, and every
    // attempt to write that stripping inline in this repository has lost an
    // escape in transit.
    const code = withoutComments(src);
    if (VERIFIERS.some((verifier) => code.includes(verifier))) found.push([file, src]);
  }
  return found;
}

test("every route that checks a secret is throttled", () => {
  const routes = credentialRoutes();
  // Both known sign-in paths must be among them, or the scan has stopped
  // finding what it is for and everything below is vacuous.
  const names = routes.map(([file]) => file).sort();
  // connections.ts joined the list when TikTok sign-in landed: it verifies an
  // HMAC over a state cookie, which is cryptography on caller-supplied input,
  // and the scan is deliberately blind to how unlikely forging it would be.
  // The right response was to throttle it, not to exempt it.
  assert.deepEqual(names, ["admin-auth.ts", "connections.ts", "employee-auth.ts"],
    `the credential-route scan found ${names.join(", ") || "nothing"} — if a new sign-in path was ` +
    `added, throttle it and add it here; if a verifier was renamed, update VERIFIERS`);

  for (const [name, src] of routes) {
    assert.match(src, /const source = clientKey\(c\.req\.raw\.headers\);/, `${name} reads no source`);
    assert.match(src, /if \(await loginBlocked\(source\)\) \{/, `${name} does not check the throttle`);
    assert.match(src, /429/, `${name} does not refuse with 429`);
  }
});

test("it counts per SOURCE and never per account", () => {
  // Locking an identifier after N failures is the obvious design and it hands
  // anybody a way to lock the owner out of their own console by typing their
  // email wrongly ten times. A limiter that becomes a denial of service against
  // the person it protects is not a security control.
  assert.match(THROTTLE, /const key = \(source: string\) => `nexus:login-failures:\$\{source\}`;/);

  // The identifier is passed only so the log line can name it.
  assert.match(THROTTLE, /recordLoginFailure\(source: string, identifier: string\)/);
  assert.ok(
    !/`nexus:login-failures:\$\{identifier\}`/.test(THROTTLE),
    "the identifier must never be part of the key"
  );
});

test("it fails OPEN, unlike the bootstrap check which fails closed", () => {
  // Different things are load-bearing. sharedPasswordRetired guards a KNOWN weak
  // credential, so denying on error is safe. This is defence in depth over a
  // credential still verified by scrypt either way — so a Redis blip must not
  // lock two admins out of the platform they run.
  const blocked = THROTTLE.slice(THROTTLE.indexOf("export async function loginBlocked"));
  assert.match(blocked.slice(0, 500), /catch \(err\) \{[\s\S]*?return false;/);
});

test("the throttle is checked BEFORE the credential is verified", () => {
  // A refused source should cost one Redis read, not an scrypt verification —
  // otherwise the limiter hands an attacker a cheap way to burn CPU.
  for (const src of [ADMIN, EMPLOYEE]) {
    const checkAt = src.indexOf("loginBlocked(source)");
    const verifyAt = Math.max(src.indexOf("verifySecret("), src.indexOf("verifyAccessCode("));
    assert.ok(checkAt > 0 && checkAt < verifyAt, "the throttle must be checked first");
  }
});

test("a success clears the count", () => {
  // Without this, somebody who mistypes nine times and then gets it right is one
  // typo from a lockout for the rest of the window — exactly the person this is
  // not aimed at.
  for (const src of [ADMIN, EMPLOYEE]) {
    assert.match(src, /await clearLoginFailures\(source\);/);
  }
});

test("the Caddyfile does not turn the forwarded address into a client-controlled one", () => {
  // The whole throttle rests on Caddy REPLACING X-Forwarded-For, which it does
  // for untrusted clients by default — verified in production by sending three
  // forged values from one machine and watching all three stay refused.
  //
  // Adding `trusted_proxies` makes Caddy APPEND instead, the first entry becomes
  // whatever the client sent, and the throttle is bypassed by rotating one
  // header: no error, no failing test, nothing changed on this side. The
  // Caddyfile is a different file in a different language with no reference to
  // this code, so the connection is asserted here or nowhere.
  const caddy = read("Caddyfile");
  assert.ok(
    !/trusted_proxies/.test(caddy),
    "trusted_proxies makes X-Forwarded-For client-controlled — the throttle must be re-checked before adding it"
  );
});

test("the client is the FIRST forwarded address, not the last", () => {
  // x-forwarded-for is a list: client first, proxies after. Taking the last
  // counts every attempt against Caddy's own address and throttles the entire
  // platform after ten failures by anybody.
  assert.match(THROTTLE, /forwarded\?\.split\(","\)\[0\]\?\.trim\(\)/);

  // A request with no header did not come through the proxy, which here means
  // it came from inside the compose network. Those share one bucket under a
  // name that says so rather than being exempted.
  assert.match(THROTTLE, /: "internal"/);
});
